---
title: "Aggro Token Druid"
author: "MalditoBarbudo"
date: "7 de mayo de 2017"
output: html_document
---

```{r config, include=FALSE}
# chunk options
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width = 8)

# libraries
library(tidyverse)
library(forcats)
library(cowplot)
```

```{r data_load, echo=FALSE, message=FALSE}
# data
data_aggro <- read_csv2('../Old_Data/aggro_druid.csv') %>%
  filter(Disconnect == 'No')
```


# Aggro Token Druid Progress

## May 2017

```{r rank_plot}
data_aggro %>%
  mutate(Id_game = 1:length(Date)) %>%
  ggplot(aes(x = Id_game, y = Rank)) +
    ylim(25,0) +
    geom_line(color = 'firebrick') +
    geom_point(aes(colour = Result)) +
    labs(x = 'Game',
         title = 'Rank progression') +
    theme_hs
```

```{r win_ratio}
overall <- data_aggro %>%
  # as_factor(Result) %>%
  mutate(win_ratio = if_else(Result == 'Win', 1, 0,
                             NA_real_)) %>%
  summarise(Ratio = mean(win_ratio)) %>%
  mutate(Opponent = 'Overall')

data_aggro %>%
  mutate(win_ratio = if_else(Result == 'Win', 1, 0,
                             NA_real_)) %>%
  group_by(Opponent) %>%
  summarise(Ratio = mean(win_ratio),
            Count = n()) %>%
  filter(Count > 3) %>%
  bind_rows(overall) %>%
  ggplot(aes(y = Ratio, x = fct_relevel(Opponent, "Overall", after = Inf),
             fill = Opponent)) +
    geom_ribbon(aes(x = fct_relevel(Opponent, "Overall", after = Inf)), ymin = 0.33, ymax = 0.5, fill = 'orange', alpha = 0.3) +
    geom_ribbon(ymin = 0, ymax = 0.33, fill = 'red', alpha = 0.3) +
    geom_ribbon(ymin = 0.5, ymax = 0.66, fill = 'darkgreen', alpha = 0.3) +
    geom_ribbon(ymin = 0.66, ymax = 1, fill = 'green', alpha = 0.3) +
    geom_hline(yintercept = 0.5, color = 'red') +
    geom_bar(stat = 'identity') +
    geom_text(aes(label = round(Ratio, 2)), vjust = 1.2) +
    scale_y_continuous(breaks = c(0, 0.33, 0.5, 0.66, 1), limits = c(0,1)) +
    labs(x = 'Opponent',
         title = 'Win Ratio per Archetype',
         subtitle = '(only archetypes with > 3 games)') +
    # coord_flip() +
    theme_hs +
    theme(legend.position = 'none') +
    theme(axis.text.x = element_text(angle = 90))
```

```{r vs_archetypes}
data_aggro %>%
  ggplot(aes(x = Opponent, fill = Result)) +
  geom_bar(position = 'stack') +
  labs(y = 'Count', x = '',
       title = 'Games per Archetype') +
  theme_hs +
  theme(axis.text.x = element_text(angle = 90))
```

```{r specific_cards}
LivingMana_total <- data_aggro %>%
  ggplot(aes(x = LivingMana, fill = Result)) +
  geom_bar(position = 'stack') +
  labs(y = 'Count', x = '',
       title = 'Living Mana') +
  theme_hs

Finja_total <- data_aggro %>%
  ggplot(aes(x = Finja, fill = Result)) +
  geom_bar(position = 'stack') +
  labs(y = 'Count', x = '',
       title = 'Finja') +
  theme_hs

Combinations <- data_aggro %>%
  mutate(Card_combo = fct_recode(as_factor(paste0(LivingMana, Finja)),
                                 None = 'NoNo', LivingMana = 'YesNo',
                                 Finja = 'NoYes', Both = 'YesYes')) %>%
  ggplot(aes(x = Card_combo, fill = Result)) +
  geom_bar(position = 'stack') +
  labs(y = 'Count', x = '',
       title = 'Detailed') +
  theme_hs

upper_grid <- plot_grid(LivingMana_total, Finja_total, labels = 'auto')
plot_grid(upper_grid, Combinations, labels = c('', 'c'),
          ncol = 1)
```

```{r prob_card_combo, fig.height=6}
overall_win_prob <- data_aggro %>%
  mutate(win_ratio = if_else(Result == 'Win', 1, 0,
                             NA_real_)) %>%
  # group_by(Turn) %>%
  # summarise(Mean = mean(win_ratio), Median = median(win_ratio), Count = n(),
  #           SD = sd(win_ratio), SE = SD/sqrt(Count + 1)) %>%
  ggplot(aes(x = Turn, y = win_ratio)) +
    geom_ribbon(ymin = 0.33, ymax = 0.5, fill = 'orange', alpha = 0.3) +
    geom_ribbon(ymin = 0, ymax = 0.33, fill = 'red', alpha = 0.3) +
    geom_ribbon(ymin = 0.5, ymax = 0.66, fill = 'darkgreen', alpha = 0.3) +
    geom_ribbon(ymin = 0.66, ymax = 1, fill = 'green', alpha = 0.3) +
    geom_hline(yintercept = .5, color = 'red', size = 1) +
    geom_jitter(alpha = .5, width = 0.07, height = 0.01) +
    stat_smooth(method = 'glm',
                method.args = list(family = "binomial"), se = FALSE,
                colour = 'darkblue') +
    scale_x_continuous(breaks = c(2:10)) +
    labs(y = 'Ratio',
         title = 'Overall probabilistic smooth',
         subtitle = '(dots are jittered for better visualization)') +
    theme_hs

card_win_prob <- data_aggro %>%
  mutate(Card_combo = fct_recode(as_factor(paste0(LivingMana, Finja)),
                                 None = 'NoNo', LivingMana = 'YesNo',
                                 Finja = 'NoYes', Both = 'YesYes'),
         win_ratio = if_else(Result == 'Win', 1, 0,
                             NA_real_)) %>%
  # group_by(Turn) %>%
  # summarise(Mean = mean(win_ratio), Median = median(win_ratio), Count = n(),
  #           SD = sd(win_ratio), SE = SD/sqrt(Count + 1)) %>%
  ggplot(aes(x = Turn, y = win_ratio)) +
    geom_ribbon(ymin = 0.33, ymax = 0.5, fill = 'orange', alpha = 0.3) +
    geom_ribbon(ymin = 0, ymax = 0.33, fill = 'red', alpha = 0.3) +
    geom_ribbon(ymin = 0.5, ymax = 0.66, fill = 'darkgreen', alpha = 0.3) +
    geom_ribbon(ymin = 0.66, ymax = 1, fill = 'green', alpha = 0.3) +
    geom_hline(yintercept = .5, color = 'red', size = 1) +
    geom_jitter(alpha = .5, width = 0.07, height = 0.01) +
    stat_smooth(aes(color = Card_combo), method = 'glm',
                method.args = list(family = "binomial"), se = FALSE) +
    scale_x_continuous(breaks = c(2:10)) +
    labs(y = 'Ratio',
         title = 'By played card probabilistic smooth',
         subtitle = '(dots are jittered for better visualization)') +
    theme_hs +
    theme(legend.position = 'top')

plot_grid(overall_win_prob, card_win_prob, ncol = 1, labels = 'auto',
          align = 'v', rel_heights = c(1,1.3))
```

```{r turn_hist}
data_aggro %>%
  filter(Disconnect == 'No') %>%
  ggplot(aes(x = Turn)) +
  geom_histogram(binwidth = 1, fill = 'skyblue', color = 'black') +
  labs(x = 'Count',
       title = 'Games finished by turn') +
  scale_x_continuous(breaks = 2:10) +
  theme_hs
```

```{r prob_per_arch}
data_aggro %>%
  mutate(Card_combo = fct_recode(as_factor(paste0(LivingMana, Finja)),
                                 None = 'NoNo', LivingMana = 'YesNo',
                                 Finja = 'NoYes', Both = 'YesYes'),
         win_ratio = if_else(Result == 'Win', 1, 0,
                             NA_real_)) %>%
  # group_by(Turn) %>%
  # summarise(Mean = mean(win_ratio), Median = median(win_ratio), Count = n(),
  #           SD = sd(win_ratio), SE = SD/sqrt(Count + 1)) %>%
  ggplot(aes(x = Turn, y = win_ratio)) +
    geom_ribbon(ymin = 0.33, ymax = 0.5, fill = 'orange', alpha = 0.3) +
    geom_ribbon(ymin = 0, ymax = 0.33, fill = 'red', alpha = 0.3) +
    geom_ribbon(ymin = 0.5, ymax = 0.66, fill = 'darkgreen', alpha = 0.3) +
    geom_ribbon(ymin = 0.66, ymax = 1, fill = 'green', alpha = 0.3) +
    geom_hline(yintercept = .5, color = 'red', size = 1) +
    geom_jitter(alpha = .5, width = 0.07, height = 0.01) +
    stat_smooth(aes(color = Card_combo), method = 'glm',
                method.args = list(family = "binomial"), se = FALSE) +
    facet_wrap(~Opponent, ncol = 3) +
    scale_x_continuous(breaks = c(2:10)) +
    labs(y = 'Ratio',
         title = 'By played card probabilistic smooth',
         subtitle = '(dots are jittered for better visualization)') +
    theme_hs +
    theme(legend.position = 'top')
```

```{r}
hist_data <- data_aggro %>%
      group_by(Turn, Result) %>%
      summarise(Proportion = n()) %>%
      mutate(Proportion = Proportion/sum(Proportion))
```

